name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install Dependencies
      run: apt-get install cmake -y && mkdir build
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -B build .
    - name: make
      run: cmake --build build
    - name: test
      working-directory: build
      run: ctest
