name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build
    -name: generate
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: cmake --build .
    - name: test
      working-directory: build
      run: ctest
